### ISSUE TITLE
Generate from scratch

### ISSUE THREAD

**Issue by iamamiramine** [dvruette/figaro#10]
Is it possible to generate a new piece from scratch without providing test files as input?

**Comment by dvruette** [comment]
The intended workflow is conditional generation: Some description is provided (either hand-written, extracted from test data, or procedurally generated) and the sample is generated conditionally. One can also imagine training an unconditional model on expert descriptions in order to generate new samples unconditionally, but this was left as future work.

**Comment by iamamiramine** [comment]
Understood. Thank you for your reply.

From a code perspective, can I provide only one decription file or latent file and generate one midi file accordingly? Because in the generate code, the script prepares a new datamodule from a set of midi files before each generation. Is it possible that my prompt could be only one description or latent file?

**Comment by dvruette** [comment]
It's been a while since I've worked with the code, so I don't remember the implementation details. I'd suggest you just try and see what happens. Alternatively you can take a look at the colab demo, which works on individual descriptions.

**Comment by iamamiramine** [comment]
Alright thank you for your help! Will go by your suggestions and let you know if it works.

**Comment by dvruette** [comment]
No problem! :)

**Comment by iamamiramine** [comment]
Hello, I checked the notebook and was able to generate a sample based on one prompt only. 
Thank you!
