### ISSUE TITLE
"n_codes" and "d_latent" 

### ISSUE THREAD

**Issue by iamamiramine** [dvruette/figaro#9]
In the VQ-VAE model, you use both n_codes and d_latent. May I ask what is the difference between both?

https://github.com/dvruette/figaro/blob/1c6262308c8d4cf4a7657112af20ae8040d267c0/src/models/vae.py#L220

**Comment by dvruette** [comment]
`d_latent` determines the dimensionality of the latent space and `n_codes` determines the size of the VQ codebook, i.e. the number of different values to quantize to. `n_groups` further determines how many groups the latent vector gets split to before quantization. Hope that helps!

**Comment by iamamiramine** [comment]
Thank you! So if I want a more accurate representation of my latent vector, I would increase `n_groups` or `n_codes`, or both, right?

**Comment by dvruette** [comment]
Yes, that’s correct. If I remember correctly, the vocabulary size is `n_codes ** n_groups` and each bar is mapped to one code in the vocabulary.

**Comment by iamamiramine** [comment]
Understood. Thank you!
I also have one more question, I want to make sure I understand how VQVAE works. 
What output should I use as my final features? Is it the `latents` or is it the `codes`?

**Comment by dvruette** [comment]
It depends: If you need dense features, it's probably best to use the `latents` or at least copy the embedding layer from the trained VQ-VAE, but if you need discrete features then it's best to use the `codes`. The reasoning is that the `latents` already live in a semantic latent space whereas the `codes`, due to their discrete nature, do not.

**Comment by iamamiramine** [comment]
Thank you! This made it clear.
